In [20]:
import pandas as pd
payment = pd.read_csv('../csv-files/olist_order_payments_dataset.csv')
payment.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [21]:
payment.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [22]:
order_id_len = payment['order_id'].str.len()
standard_order_id_len = order_id_len.mode()[0]
invalid_ord_id_len = order_id_len != standard_order_id_len
print("order_id standard length:", standard_order_id_len)
print("invalid order_id length:", invalid_ord_id_len.sum())

order_id standard length: 32
invalid order_id length: 0

In [23]:
payment['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [24]:
# 1. Check if any values are text/letters (should be 0)
non_numeric = pd.to_numeric(payment['payment_value'], errors='coerce').isna().sum()

# 2. Check if any values have more than 2 decimal places
# We multiply by 100 and check if there is a remainder left over
has_extra_decimals = (payment['payment_value'] * 100 % 1 != 0)

print("Rows containing letters or text:", non_numeric)
print("Rows with more than 2 decimal places:", has_extra_decimals)

Rows containing letters or text: 0
Rows with more than 2 decimal places: 0         False
1         False
2          True
3         False
4          True
          ...
103881    False
103882    False
103883    False
103884    False
103885    False
Name: payment_value, Length: 103886, dtype: bool

In [25]:
# 1. Map 'boleto' to 'bank_slip' and leave everything else unchanged
payment['payment_type'] = payment['payment_type'].replace({'boleto': 'bank_slip'})
payment['payment_type'] = payment['payment_type'].replace({'credit_card': 'credit card'})

In [26]:
# Check installments for boleto payments
boleto_df = payment[payment['payment_type'] == 'boleto']
print(boleto_df['payment_installments'].unique())

[]

In [27]:
payment.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit card,2,128.45

In [28]:
payment.to_csv('../df_cleaned/payment_cln.csv')